param(
  [ValidateSet("core", "all")]
  [string]$Profile = "all",
  [string]$Root = ""
)

$ErrorActionPreference = "Stop"

if (!$Root) {
  $Root = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
}

$coreRoles = @("orchestrator", "market_bias", "scanner", "research", "analyst", "critic")
$allRoles = @(
  "orchestrator",
  "market_bias",
  "scanner",
  "research",
  "chart_vision",
  "analyst",
  "critic",
  "intel",
  "generator",
  "writer",
  "memory",
  "publisher"
)
$roles = if ($Profile -eq "all") { $allRoles } else { $coreRoles }

foreach ($role in $roles) {
  & "$PSScriptRoot\Start-AxlNode.ps1" -Role $role -Root $Root
}

$demoDir = Join-Path $Root "local\axl\demo"
$envPath = Join-Path $demoDir "axl-demo.env"
$peerIds = @{}

foreach ($role in $roles) {
  $peerPath = Join-Path $demoDir "$role\peer-id.txt"
  if (Test-Path $peerPath) {
    $peerIds[$role] = (Get-Content -Path $peerPath -Raw).Trim()
  }
}

if (!$peerIds.ContainsKey("orchestrator")) {
  throw "The orchestrator peer id was not captured. Check local/logs/axl-demo/orchestrator-node.err.log"
}

$envLines = @(
  "# Generated by scripts/axl/start-demo-swarm.ps1",
  "# Load these values into the backend environment for the local split-node AXL demo.",
  "AXL_NODE_BASE_URL=http://127.0.0.1:9002",
  "AXL_ORCHESTRATOR_NODE_ID=$($peerIds["orchestrator"])",
  "AXL_MARKET_BIAS_NODE_ID=$($peerIds["market_bias"])",
  "AXL_SCANNER_NODE_ID=$($peerIds["scanner"])",
  "AXL_RESEARCH_NODE_ID=$($peerIds["research"])",
  "AXL_CHART_VISION_NODE_ID=$($peerIds["chart_vision"])",
  "AXL_ANALYST_NODE_ID=$($peerIds["analyst"])",
  "AXL_CRITIC_NODE_ID=$($peerIds["critic"])",
  "AXL_INTEL_NODE_ID=$($peerIds["intel"])",
  "AXL_GENERATOR_NODE_ID=$($peerIds["generator"])",
  "AXL_WRITER_NODE_ID=$($peerIds["writer"])",
  "AXL_PUBLISHER_NODE_ID=$($peerIds["publisher"])",
  "AXL_MEMORY_NODE_ID=$($peerIds["memory"])"
)

$missingRoles = @()
foreach ($role in $roles) {
  if (!$peerIds.ContainsKey($role) -or !$peerIds[$role]) {
    $missingRoles += $role
  }
}

if ($missingRoles.Count -gt 0) {
  throw "Missing AXL peer ids for roles: $($missingRoles -join ', '). Check local/logs/axl-demo before loading backend env."
}

$envLines | Set-Content -Path $envPath -Encoding ASCII

Write-Host ""
Write-Host "AXL demo swarm started with profile: $Profile"
Write-Host "Generated backend env snippet: $envPath"
Write-Host ""
Get-Content -Path $envPath
