param(
  [ValidateSet("core", "all")]
  [string]$Profile = "all",
  [string]$Root = ""
)

$ErrorActionPreference = "Stop"

if (!$Root) {
  $Root = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
}

$coreRoles = @("orchestrator", "scanner", "research", "analyst", "critic")
$allRoles = @(
  "orchestrator",
  "market_bias",
  "scanner",
  "research",
  "chart_vision",
  "analyst",
  "critic",
  "intel",
  "generator",
  "writer",
  "memory",
  "publisher"
)
$roles = if ($Profile -eq "all") { $allRoles } else { $coreRoles }

foreach ($role in $roles) {
  & "$PSScriptRoot\Start-AxlNode.ps1" -Role $role -Root $Root
}

$demoDir = Join-Path $Root "local\axl\demo"
$envPath = Join-Path $demoDir "axl-demo.env"
$peerIds = @{}

foreach ($role in $roles) {
  $peerPath = Join-Path $demoDir "$role\peer-id.txt"
  if (Test-Path $peerPath) {
    $peerIds[$role] = (Get-Content -Path $peerPath -Raw).Trim()
  }
}

if (!$peerIds.ContainsKey("orchestrator")) {
  throw "The orchestrator peer id was not captured. Check local/logs/axl-demo/orchestrator-node.err.log"
}

function Get-PeerForRole([string]$RoleName) {
  if ($peerIds.ContainsKey($RoleName)) {
    return $peerIds[$RoleName]
  }

  return $peerIds["orchestrator"]
}

$envLines = @(
  "# Generated by scripts/axl/start-demo-swarm.ps1",
  "# Load these values into the backend environment for the local split-node AXL demo.",
  "AXL_NODE_BASE_URL=http://127.0.0.1:9002",
  "AXL_SERVICE_PEER_ID=$($peerIds["orchestrator"])",
  "AXL_ORCHESTRATOR_NODE_ID=$($peerIds["orchestrator"])",
  "AXL_MARKET_BIAS_NODE_ID=$(Get-PeerForRole "market_bias")",
  "AXL_SCANNER_NODE_ID=$(Get-PeerForRole "scanner")",
  "AXL_RESEARCH_NODE_ID=$(Get-PeerForRole "research")",
  "AXL_CHART_VISION_NODE_ID=$(Get-PeerForRole "chart_vision")",
  "AXL_ANALYST_NODE_ID=$(Get-PeerForRole "analyst")",
  "AXL_CRITIC_NODE_ID=$(Get-PeerForRole "critic")",
  "AXL_INTEL_NODE_ID=$(Get-PeerForRole "intel")",
  "AXL_GENERATOR_NODE_ID=$(Get-PeerForRole "generator")",
  "AXL_WRITER_NODE_ID=$(Get-PeerForRole "writer")",
  "AXL_PUBLISHER_NODE_ID=$(Get-PeerForRole "publisher")",
  "AXL_MEMORY_NODE_ID=$(Get-PeerForRole "memory")"
)

$envLines | Set-Content -Path $envPath -Encoding ASCII

Write-Host ""
Write-Host "AXL demo swarm started with profile: $Profile"
Write-Host "Generated backend env snippet: $envPath"
Write-Host ""
Get-Content -Path $envPath
