-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.agent_events (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  run_id text NOT NULL,
  agent_id text NOT NULL,
  agent_role text NOT NULL CHECK (agent_role = ANY (ARRAY['orchestrator'::text, 'market_bias'::text, 'scanner'::text, 'research'::text, 'chart_vision'::text, 'analyst'::text, 'critic'::text, 'intel'::text, 'publisher'::text, 'memory'::text, 'monitor'::text])),
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['run_created'::text, 'market_bias_generated'::text, 'candidate_found'::text, 'axl_message_sent'::text, 'axl_message_received'::text, 'zero_g_kv_write'::text, 'zero_g_log_append'::text, 'zero_g_file_published'::text, 'research_completed'::text, 'chart_generated'::text, 'thesis_generated'::text, 'critic_decision'::text, 'report_published'::text, 'intel_ready'::text, 'post_queued'::text, 'warning'::text, 'error'::text])),
  status text NOT NULL CHECK (status = ANY (ARRAY['info'::text, 'success'::text, 'warning'::text, 'error'::text, 'pending'::text])),
  summary text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  correlation_id text,
  axl_message_id text,
  proof_ref_id text,
  signal_id text,
  intel_id text,
  CONSTRAINT agent_events_pkey PRIMARY KEY (id),
  CONSTRAINT agent_events_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.runs(id),
  CONSTRAINT agent_events_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agent_nodes(id),
  CONSTRAINT agent_events_proof_ref_id_fkey FOREIGN KEY (proof_ref_id) REFERENCES public.zero_g_refs(id),
  CONSTRAINT agent_events_signal_id_fkey FOREIGN KEY (signal_id) REFERENCES public.signals(id),
  CONSTRAINT agent_events_intel_id_fkey FOREIGN KEY (intel_id) REFERENCES public.intels(id),
  CONSTRAINT agent_events_axl_message_id_fkey FOREIGN KEY (axl_message_id) REFERENCES public.axl_messages(id)
);
CREATE TABLE public.agent_nodes (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  role text NOT NULL CHECK (role = ANY (ARRAY['orchestrator'::text, 'market_bias'::text, 'scanner'::text, 'research'::text, 'chart_vision'::text, 'analyst'::text, 'critic'::text, 'intel'::text, 'publisher'::text, 'memory'::text, 'monitor'::text])),
  transport text NOT NULL CHECK (transport = ANY (ARRAY['axl'::text, 'local'::text])),
  status text NOT NULL CHECK (status = ANY (ARRAY['starting'::text, 'online'::text, 'degraded'::text, 'offline'::text])),
  peer_id text,
  last_heartbeat_at timestamp with time zone,
  last_error text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_nodes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.analytics_snapshots (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  run_id text,
  generated_at timestamp with time zone NOT NULL DEFAULT now(),
  totals jsonb NOT NULL DEFAULT '{}'::jsonb,
  confidence_bands jsonb NOT NULL DEFAULT '[]'::jsonb,
  token_frequency jsonb NOT NULL DEFAULT '[]'::jsonb,
  mindshare jsonb NOT NULL DEFAULT '[]'::jsonb,
  win_rate numeric,
  CONSTRAINT analytics_snapshots_pkey PRIMARY KEY (id),
  CONSTRAINT analytics_snapshots_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.runs(id)
);
CREATE TABLE public.app_config (
  id text NOT NULL DEFAULT 'default'::text,
  mode text NOT NULL CHECK (mode = ANY (ARRAY['mocked'::text, 'live'::text, 'production_like'::text])),
  market_universe jsonb NOT NULL DEFAULT '[]'::jsonb,
  quality_thresholds jsonb NOT NULL DEFAULT '{}'::jsonb,
  providers jsonb NOT NULL DEFAULT '{}'::jsonb,
  paper_trading_enabled boolean NOT NULL DEFAULT true,
  testnet_execution_enabled boolean NOT NULL DEFAULT false,
  mainnet_execution_enabled boolean NOT NULL DEFAULT false,
  post_to_x_enabled boolean NOT NULL DEFAULT false,
  scan_interval_minutes integer NOT NULL DEFAULT 60 CHECK (scan_interval_minutes >= 1),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT app_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.axl_messages (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  run_id text NOT NULL,
  correlation_id text NOT NULL,
  from_agent_id text NOT NULL,
  from_role text NOT NULL CHECK (from_role = ANY (ARRAY['orchestrator'::text, 'market_bias'::text, 'scanner'::text, 'research'::text, 'chart_vision'::text, 'analyst'::text, 'critic'::text, 'intel'::text, 'publisher'::text, 'memory'::text, 'monitor'::text])),
  to_agent_id text,
  to_role text CHECK (to_role = ANY (ARRAY['orchestrator'::text, 'market_bias'::text, 'scanner'::text, 'research'::text, 'chart_vision'::text, 'analyst'::text, 'critic'::text, 'intel'::text, 'publisher'::text, 'memory'::text, 'monitor'::text])),
  topic text,
  message_type text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  transport_kind text NOT NULL CHECK (transport_kind = ANY (ARRAY['send'::text, 'a2a'::text, 'mcp'::text])),
  delivery_status text NOT NULL CHECK (delivery_status = ANY (ARRAY['queued'::text, 'sent'::text, 'received'::text, 'failed'::text])),
  durable_ref_id text,
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT axl_messages_pkey PRIMARY KEY (id),
  CONSTRAINT axl_messages_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.runs(id),
  CONSTRAINT axl_messages_from_agent_id_fkey FOREIGN KEY (from_agent_id) REFERENCES public.agent_nodes(id),
  CONSTRAINT axl_messages_to_agent_id_fkey FOREIGN KEY (to_agent_id) REFERENCES public.agent_nodes(id),
  CONSTRAINT axl_messages_durable_ref_id_fkey FOREIGN KEY (durable_ref_id) REFERENCES public.zero_g_refs(id)
);
CREATE TABLE public.intels (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  run_id text NOT NULL,
  title text NOT NULL,
  slug text NOT NULL UNIQUE,
  summary text NOT NULL,
  body text NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['market_update'::text, 'narrative_shift'::text, 'token_watch'::text, 'macro'::text, 'opportunity'::text])),
  status text NOT NULL CHECK (status = ANY (ARRAY['draft'::text, 'ready'::text, 'published'::text, 'suppressed'::text])),
  symbols jsonb NOT NULL DEFAULT '[]'::jsonb,
  confidence integer NOT NULL CHECK (confidence >= 0 AND confidence <= 100),
  sources jsonb NOT NULL DEFAULT '[]'::jsonb,
  proof_ref_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  published_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT intels_pkey PRIMARY KEY (id),
  CONSTRAINT intels_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.runs(id)
);
CREATE TABLE public.outbound_posts (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  run_id text NOT NULL,
  signal_id text,
  intel_id text,
  target text NOT NULL CHECK (target = 'x'::text),
  kind text NOT NULL CHECK (kind = ANY (ARRAY['signal_alert'::text, 'intel_summary'::text, 'intel_thread'::text])),
  status text NOT NULL CHECK (status = ANY (ARRAY['queued'::text, 'formatting'::text, 'ready'::text, 'posting'::text, 'posted'::text, 'failed'::text])),
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  provider text NOT NULL,
  provider_post_id text,
  published_url text,
  last_error text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  published_at timestamp with time zone,
  CONSTRAINT outbound_posts_pkey PRIMARY KEY (id),
  CONSTRAINT outbound_posts_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.runs(id),
  CONSTRAINT outbound_posts_signal_id_fkey FOREIGN KEY (signal_id) REFERENCES public.signals(id),
  CONSTRAINT outbound_posts_intel_id_fkey FOREIGN KEY (intel_id) REFERENCES public.intels(id)
);
CREATE TABLE public.runs (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  mode text NOT NULL CHECK (mode = ANY (ARRAY['mocked'::text, 'live'::text, 'production_like'::text])),
  status text NOT NULL CHECK (status = ANY (ARRAY['queued'::text, 'starting'::text, 'running'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])),
  market_bias text NOT NULL DEFAULT 'UNKNOWN'::text CHECK (market_bias = ANY (ARRAY['LONG'::text, 'SHORT'::text, 'NEUTRAL'::text, 'UNKNOWN'::text])),
  triggered_by text NOT NULL CHECK (triggered_by = ANY (ARRAY['dashboard'::text, 'scheduler'::text, 'system'::text])),
  active_candidate_count integer NOT NULL DEFAULT 0 CHECK (active_candidate_count >= 0 AND active_candidate_count <= 3),
  current_checkpoint_ref_id text,
  final_signal_id text,
  final_intel_id text,
  failure_reason text,
  outcome jsonb,
  config_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT runs_pkey PRIMARY KEY (id),
  CONSTRAINT runs_final_signal_id_fkey FOREIGN KEY (final_signal_id) REFERENCES public.signals(id),
  CONSTRAINT runs_final_intel_id_fkey FOREIGN KEY (final_intel_id) REFERENCES public.intels(id),
  CONSTRAINT runs_current_checkpoint_ref_id_fkey FOREIGN KEY (current_checkpoint_ref_id) REFERENCES public.zero_g_refs(id)
);
CREATE TABLE public.service_registry_snapshots (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  captured_at timestamp with time zone NOT NULL DEFAULT now(),
  source text NOT NULL,
  peers jsonb NOT NULL DEFAULT '[]'::jsonb,
  services jsonb NOT NULL DEFAULT '[]'::jsonb,
  routes jsonb NOT NULL DEFAULT '[]'::jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT service_registry_snapshots_pkey PRIMARY KEY (id)
);
CREATE TABLE public.signals (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  run_id text NOT NULL,
  candidate_id text,
  asset text NOT NULL,
  direction text NOT NULL CHECK (direction = ANY (ARRAY['LONG'::text, 'SHORT'::text, 'WATCHLIST'::text, 'NONE'::text])),
  confidence integer NOT NULL CHECK (confidence >= 0 AND confidence <= 100),
  risk_reward numeric,
  entry_zone jsonb,
  invalidation jsonb,
  targets jsonb NOT NULL DEFAULT '[]'::jsonb,
  why_now text NOT NULL,
  confluences jsonb NOT NULL DEFAULT '[]'::jsonb,
  uncertainty_notes text NOT NULL,
  missing_data_notes text NOT NULL,
  critic_decision text NOT NULL CHECK (critic_decision = ANY (ARRAY['approved'::text, 'rejected'::text, 'watchlist_only'::text])),
  report_status text NOT NULL CHECK (report_status = ANY (ARRAY['draft'::text, 'published'::text, 'superseded'::text])),
  final_report_ref_id text,
  proof_ref_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  disclaimer text NOT NULL,
  published_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT signals_pkey PRIMARY KEY (id),
  CONSTRAINT signals_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.runs(id),
  CONSTRAINT signals_final_report_ref_id_fkey FOREIGN KEY (final_report_ref_id) REFERENCES public.zero_g_refs(id)
);
CREATE TABLE public.zero_g_refs (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  run_id text NOT NULL,
  signal_id text,
  intel_id text,
  ref_type text NOT NULL CHECK (ref_type = ANY (ARRAY['kv_state'::text, 'log_entry'::text, 'log_bundle'::text, 'file_artifact'::text, 'compute_job'::text, 'compute_result'::text, 'post_payload'::text, 'post_result'::text, 'manifest'::text, 'chain_proof'::text])),
  key text,
  locator text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT zero_g_refs_pkey PRIMARY KEY (id),
  CONSTRAINT zero_g_refs_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.runs(id),
  CONSTRAINT zero_g_refs_signal_id_fkey FOREIGN KEY (signal_id) REFERENCES public.signals(id),
  CONSTRAINT zero_g_refs_intel_id_fkey FOREIGN KEY (intel_id) REFERENCES public.intels(id)
);