import {
  OMEN_DISCLAIMER,
  agentEventSchema,
  agentNodeSchema,
  axlEnvelopeSchema,
  intelSchema,
  outboundPostSchema,
  proofArtifactSchema,
  runProofBundleSchema,
  runSchema,
  signalSchema,
} from "@omen/shared";
import { z } from "zod";

import {
  DEMO_INTEL_RUN_COMPLETED_AT,
  DEMO_INTEL_RUN_STARTED_AT,
  DEMO_SIGNAL_RUN_COMPLETED_AT,
  DEMO_SIGNAL_RUN_STARTED_AT,
  demoRuntimeConfig,
} from "./demo-config.js";

export const demoAgentNodes = z
  .array(agentNodeSchema)
  .parse([
    {
      id: "agent-orchestrator-001",
      role: "orchestrator",
      transport: "axl",
      status: "online",
      peerId: "peer-orchestrator",
      lastHeartbeatAt: DEMO_INTEL_RUN_COMPLETED_AT,
      lastError: null,
      metadata: { region: "local", services: ["runtime.plan", "runtime.dispatch"] },
    },
    {
      id: "agent-scanner-001",
      role: "scanner",
      transport: "axl",
      status: "online",
      peerId: "peer-scanner",
      lastHeartbeatAt: DEMO_INTEL_RUN_COMPLETED_AT,
      lastError: null,
      metadata: { region: "local", services: ["scanner.scan"] },
    },
    {
      id: "agent-research-001",
      role: "research",
      transport: "axl",
      status: "online",
      peerId: "peer-research",
      lastHeartbeatAt: DEMO_INTEL_RUN_COMPLETED_AT,
      lastError: null,
      metadata: { region: "local", services: ["research.bundle"] },
    },
    {
      id: "agent-analyst-001",
      role: "analyst",
      transport: "axl",
      status: "online",
      peerId: "peer-analyst",
      lastHeartbeatAt: DEMO_INTEL_RUN_COMPLETED_AT,
      lastError: null,
      metadata: { region: "local", services: ["analyst.thesis"] },
    },
    {
      id: "agent-critic-001",
      role: "critic",
      transport: "axl",
      status: "online",
      peerId: "peer-critic",
      lastHeartbeatAt: DEMO_INTEL_RUN_COMPLETED_AT,
      lastError: null,
      metadata: { region: "local", services: ["critic.review"] },
    },
    {
      id: "agent-publisher-001",
      role: "publisher",
      transport: "local",
      status: "online",
      peerId: null,
      lastHeartbeatAt: DEMO_INTEL_RUN_COMPLETED_AT,
      lastError: null,
      metadata: { region: "backend", services: ["publisher.format"] },
    },
    {
      id: "agent-memory-001",
      role: "memory",
      transport: "local",
      status: "online",
      peerId: null,
      lastHeartbeatAt: DEMO_INTEL_RUN_COMPLETED_AT,
      lastError: null,
      metadata: { region: "backend", services: ["memory.checkpoint"] },
    },
  ]);

const signalRun = runSchema.parse({
  id: "run-signal-001",
  mode: "mocked",
  status: "completed",
  marketBias: "LONG",
  startedAt: DEMO_SIGNAL_RUN_STARTED_AT,
  completedAt: DEMO_SIGNAL_RUN_COMPLETED_AT,
  triggeredBy: "scheduler",
  activeCandidateCount: 2,
  currentCheckpointRefId: "proof-signal-kv-001",
  finalSignalId: "signal-btc-long-001",
  finalIntelId: null,
  failureReason: null,
  outcome: {
    outcomeType: "signal",
    summary: "BTC long setup approved after scanner, analyst, and critic convergence.",
    signalId: "signal-btc-long-001",
    intelId: null,
  },
  configSnapshot: demoRuntimeConfig,
  createdAt: DEMO_SIGNAL_RUN_STARTED_AT,
  updatedAt: DEMO_SIGNAL_RUN_COMPLETED_AT,
});

const signalProofArtifacts = z.array(proofArtifactSchema).parse([
  {
    id: "proof-signal-kv-001",
    runId: signalRun.id,
    signalId: "signal-btc-long-001",
    intelId: null,
    refType: "kv_state",
    key: "runs/run-signal-001/checkpoint",
    locator: "0g://kv/runs/run-signal-001/checkpoint",
    metadata: { checkpoint: "critic-approved", provider: "0g-storage-kv" },
    compute: null,
    createdAt: "2026-04-25T08:05:00.000Z",
  },
  {
    id: "proof-signal-log-001",
    runId: signalRun.id,
    signalId: "signal-btc-long-001",
    intelId: null,
    refType: "log_bundle",
    key: "runs/run-signal-001/debate",
    locator: "0g://log/runs/run-signal-001/debate",
    metadata: { entries: 18, provider: "0g-storage-log" },
    compute: null,
    createdAt: "2026-04-25T08:05:15.000Z",
  },
  {
    id: "proof-signal-compute-001",
    runId: signalRun.id,
    signalId: "signal-btc-long-001",
    intelId: null,
    refType: "compute_result",
    key: "runs/run-signal-001/final-adjudication",
    locator: "0g://compute/jobs/job-signal-001/result",
    metadata: { step: "final_adjudication" },
    compute: {
      provider: "0g-compute",
      model: "glm-5",
      jobId: "job-signal-001",
      requestHash: "req-signal-001",
      responseHash: "res-signal-001",
      verificationMode: "tee",
    },
    createdAt: "2026-04-25T08:05:30.000Z",
  },
  {
    id: "proof-signal-manifest-001",
    runId: signalRun.id,
    signalId: "signal-btc-long-001",
    intelId: null,
    refType: "manifest",
    key: "runs/run-signal-001/manifest",
    locator: "0g://file/runs/run-signal-001/manifest.json",
    metadata: { artifactCount: 5 },
    compute: null,
    createdAt: DEMO_SIGNAL_RUN_COMPLETED_AT,
  },
  {
    id: "proof-signal-post-001",
    runId: signalRun.id,
    signalId: "signal-btc-long-001",
    intelId: null,
    refType: "post_result",
    key: "runs/run-signal-001/post-result",
    locator: "0g://file/runs/run-signal-001/post-result.json",
    metadata: { provider: "twitterapi" },
    compute: null,
    createdAt: "2026-04-25T08:06:10.000Z",
  },
]);

const signalRecord = signalSchema.parse({
  id: "signal-btc-long-001",
  runId: signalRun.id,
  candidateId: "candidate-btc-breakout-001",
  asset: "BTC",
  direction: "LONG",
  confidence: 91,
  riskReward: 2.8,
  entryZone: {
    low: 92450,
    high: 92800,
    rationale: "Retest of intraday breakout zone",
  },
  invalidation: {
    low: 91550,
    high: 91800,
    rationale: "Loss of breakout structure invalidates thesis",
  },
  targets: [
    { label: "TP1", price: 93900 },
    { label: "TP2", price: 94850 },
  ],
  whyNow: "BTC reclaimed range highs while funding stayed contained and spot-led strength held across majors.",
  confluences: [
    "4H breakout above local resistance",
    "Positive spot-led order flow",
    "Critic-approved risk/reward above threshold",
  ],
  uncertaintyNotes: "Macro headlines can still interrupt follow-through if US rates commentary turns risk-off.",
  missingDataNotes: "Order-book depth was estimated from fallback market snapshots instead of direct exchange L2.",
  criticDecision: "approved",
  reportStatus: "published",
  finalReportRefId: "proof-signal-manifest-001",
  proofRefIds: signalProofArtifacts.map((artifact) => artifact.id),
  disclaimer: OMEN_DISCLAIMER,
  publishedAt: "2026-04-25T08:06:10.000Z",
  createdAt: "2026-04-25T08:04:30.000Z",
  updatedAt: "2026-04-25T08:06:10.000Z",
});

const signalMessages = z.array(axlEnvelopeSchema).parse([
  {
    id: "axl-signal-001",
    runId: signalRun.id,
    correlationId: "corr-signal-001",
    fromAgentId: "agent-orchestrator-001",
    fromRole: "orchestrator",
    toAgentId: "agent-scanner-001",
    toRole: "scanner",
    topic: null,
    messageType: "scan.request",
    payload: { universe: demoRuntimeConfig.marketUniverse, bias: "LONG" },
    transportKind: "mcp",
    deliveryStatus: "received",
    durableRefId: null,
    timestamp: "2026-04-25T08:00:15.000Z",
  },
  {
    id: "axl-signal-002",
    runId: signalRun.id,
    correlationId: "corr-signal-002",
    fromAgentId: "agent-scanner-001",
    fromRole: "scanner",
    toAgentId: "agent-research-001",
    toRole: "research",
    topic: null,
    messageType: "candidate.promote",
    payload: { symbol: "BTC", candidateId: "candidate-btc-breakout-001" },
    transportKind: "a2a",
    deliveryStatus: "received",
    durableRefId: "proof-signal-log-001",
    timestamp: "2026-04-25T08:01:20.000Z",
  },
  {
    id: "axl-signal-003",
    runId: signalRun.id,
    correlationId: "corr-signal-003",
    fromAgentId: "agent-analyst-001",
    fromRole: "analyst",
    toAgentId: "agent-critic-001",
    toRole: "critic",
    topic: null,
    messageType: "thesis.review",
    payload: { thesisId: "thesis-btc-long-001", candidateId: "candidate-btc-breakout-001" },
    transportKind: "send",
    deliveryStatus: "received",
    durableRefId: "proof-signal-compute-001",
    timestamp: "2026-04-25T08:04:45.000Z",
  },
]);

const signalEvents = z.array(agentEventSchema).parse([
  {
    id: "event-signal-001",
    runId: signalRun.id,
    agentId: "agent-orchestrator-001",
    agentRole: "orchestrator",
    eventType: "run_created",
    status: "success",
    summary: "Hourly mocked signal run created.",
    payload: { runMode: "mocked" },
    timestamp: DEMO_SIGNAL_RUN_STARTED_AT,
    correlationId: null,
    axlMessageId: null,
    proofRefId: null,
    signalId: null,
    intelId: null,
  },
  {
    id: "event-signal-002",
    runId: signalRun.id,
    agentId: "agent-scanner-001",
    agentRole: "scanner",
    eventType: "candidate_found",
    status: "success",
    summary: "Scanner shortlisted BTC and ETH for deeper analysis.",
    payload: { candidates: ["BTC", "ETH"] },
    timestamp: "2026-04-25T08:01:10.000Z",
    correlationId: "corr-signal-001",
    axlMessageId: "axl-signal-001",
    proofRefId: null,
    signalId: null,
    intelId: null,
  },
  {
    id: "event-signal-003",
    runId: signalRun.id,
    agentId: "agent-research-001",
    agentRole: "research",
    eventType: "research_completed",
    status: "success",
    summary: "Research bundle finished for BTC breakout candidate.",
    payload: { candidateId: "candidate-btc-breakout-001", evidenceCount: 4 },
    timestamp: "2026-04-25T08:03:15.000Z",
    correlationId: "corr-signal-002",
    axlMessageId: "axl-signal-002",
    proofRefId: "proof-signal-log-001",
    signalId: null,
    intelId: null,
  },
  {
    id: "event-signal-004",
    runId: signalRun.id,
    agentId: "agent-critic-001",
    agentRole: "critic",
    eventType: "critic_decision",
    status: "success",
    summary: "Critic approved BTC long thesis for publishing.",
    payload: { decision: "approved", riskReward: 2.8 },
    timestamp: "2026-04-25T08:05:30.000Z",
    correlationId: "corr-signal-003",
    axlMessageId: "axl-signal-003",
    proofRefId: "proof-signal-compute-001",
    signalId: "signal-btc-long-001",
    intelId: null,
  },
  {
    id: "event-signal-005",
    runId: signalRun.id,
    agentId: "agent-memory-001",
    agentRole: "memory",
    eventType: "zero_g_kv_write",
    status: "success",
    summary: "Latest checkpoint written to 0G KV.",
    payload: { key: "runs/run-signal-001/checkpoint" },
    timestamp: "2026-04-25T08:05:40.000Z",
    correlationId: null,
    axlMessageId: null,
    proofRefId: "proof-signal-kv-001",
    signalId: "signal-btc-long-001",
    intelId: null,
  },
  {
    id: "event-signal-006",
    runId: signalRun.id,
    agentId: "agent-publisher-001",
    agentRole: "publisher",
    eventType: "report_published",
    status: "success",
    summary: "Signal alert posted to X and linked into the run manifest.",
    payload: { provider: "twitterapi" },
    timestamp: "2026-04-25T08:06:10.000Z",
    correlationId: null,
    axlMessageId: null,
    proofRefId: "proof-signal-post-001",
    signalId: "signal-btc-long-001",
    intelId: null,
  },
]);

const signalPost = outboundPostSchema.parse({
  id: "post-signal-001",
  runId: signalRun.id,
  signalId: signalRecord.id,
  intelId: null,
  target: "x",
  kind: "signal_alert",
  status: "posted",
  payload: {
    text: "Omen signal: BTC LONG 92.45k-92.8k, invalidation 91.55k, TP 93.9k / 94.85k. Informational only.",
    thread: [],
    metadata: { manifestRefId: "proof-signal-manifest-001" },
  },
  provider: "twitterapi",
  providerPostId: "tweet-signal-001",
  publishedUrl: "https://x.com/omen/status/1000000000000000001",
  lastError: null,
  createdAt: "2026-04-25T08:05:50.000Z",
  updatedAt: "2026-04-25T08:06:10.000Z",
  publishedAt: "2026-04-25T08:06:10.000Z",
});

const signalProofBundle = runProofBundleSchema.parse({
  runId: signalRun.id,
  manifestRefId: "proof-signal-manifest-001",
  artifactRefs: signalProofArtifacts,
});

const intelRun = runSchema.parse({
  id: "run-intel-001",
  mode: "mocked",
  status: "completed",
  marketBias: "NEUTRAL",
  startedAt: DEMO_INTEL_RUN_STARTED_AT,
  completedAt: DEMO_INTEL_RUN_COMPLETED_AT,
  triggeredBy: "scheduler",
  activeCandidateCount: 1,
  currentCheckpointRefId: "proof-intel-kv-001",
  finalSignalId: null,
  finalIntelId: "intel-ai-rotation-001",
  failureReason: null,
  outcome: {
    outcomeType: "intel",
    summary: "Narrative intel published on AI infrastructure rotation.",
    signalId: null,
    intelId: "intel-ai-rotation-001",
  },
  configSnapshot: demoRuntimeConfig,
  createdAt: DEMO_INTEL_RUN_STARTED_AT,
  updatedAt: DEMO_INTEL_RUN_COMPLETED_AT,
});

const intelProofArtifacts = z.array(proofArtifactSchema).parse([
  {
    id: "proof-intel-kv-001",
    runId: intelRun.id,
    signalId: null,
    intelId: "intel-ai-rotation-001",
    refType: "kv_state",
    key: "runs/run-intel-001/checkpoint",
    locator: "0g://kv/runs/run-intel-001/checkpoint",
    metadata: { checkpoint: "intel-ready" },
    compute: null,
    createdAt: "2026-04-25T09:03:10.000Z",
  },
  {
    id: "proof-intel-log-001",
    runId: intelRun.id,
    signalId: null,
    intelId: "intel-ai-rotation-001",
    refType: "log_bundle",
    key: "runs/run-intel-001/trace",
    locator: "0g://log/runs/run-intel-001/trace",
    metadata: { entries: 11 },
    compute: null,
    createdAt: "2026-04-25T09:03:20.000Z",
  },
  {
    id: "proof-intel-manifest-001",
    runId: intelRun.id,
    signalId: null,
    intelId: "intel-ai-rotation-001",
    refType: "manifest",
    key: "runs/run-intel-001/manifest",
    locator: "0g://file/runs/run-intel-001/manifest.json",
    metadata: { artifactCount: 4 },
    compute: null,
    createdAt: DEMO_INTEL_RUN_COMPLETED_AT,
  },
  {
    id: "proof-intel-post-001",
    runId: intelRun.id,
    signalId: null,
    intelId: "intel-ai-rotation-001",
    refType: "post_result",
    key: "runs/run-intel-001/post-result",
    locator: "0g://file/runs/run-intel-001/post-result.json",
    metadata: { provider: "twitterapi" },
    compute: null,
    createdAt: "2026-04-25T09:04:20.000Z",
  },
]);

const intelRecord = intelSchema.parse({
  id: "intel-ai-rotation-001",
  runId: intelRun.id,
  title: "AI Infrastructure Names Keep Absorbing Attention While Majors Chop",
  slug: "ai-infrastructure-rotation-2026-04-25",
  summary: "Omen detected sustained attention rotation into AI-linked infrastructure tokens while BTC stayed rangebound.",
  body: "Market breadth stayed mixed, but AI-linked infrastructure symbols kept outpacing majors on both mindshare and relative strength. The swarm treated it as intel rather than a trade because BTC posture stayed neutral and catalyst confirmation was narrative-led.",
  category: "narrative_shift",
  status: "published",
  symbols: ["TAO", "RNDR", "AKT"],
  confidence: 88,
  sources: [
    {
      label: "AI infrastructure narrative thread",
      url: "https://example.com/ai-rotation",
      provider: "news",
    },
    {
      label: "Mindshare snapshot",
      url: null,
      provider: "defillama",
    },
  ],
  proofRefIds: intelProofArtifacts.map((artifact) => artifact.id),
  publishedAt: "2026-04-25T09:04:20.000Z",
  createdAt: "2026-04-25T09:02:30.000Z",
  updatedAt: "2026-04-25T09:04:20.000Z",
});

const intelMessages = z.array(axlEnvelopeSchema).parse([
  {
    id: "axl-intel-001",
    runId: intelRun.id,
    correlationId: "corr-intel-001",
    fromAgentId: "agent-orchestrator-001",
    fromRole: "orchestrator",
    toAgentId: "agent-research-001",
    toRole: "research",
    topic: null,
    messageType: "intel.research",
    payload: { focus: "narrative_rotation" },
    transportKind: "mcp",
    deliveryStatus: "received",
    durableRefId: null,
    timestamp: "2026-04-25T09:00:25.000Z",
  },
  {
    id: "axl-intel-002",
    runId: intelRun.id,
    correlationId: "corr-intel-002",
    fromAgentId: "agent-research-001",
    fromRole: "research",
    toAgentId: "agent-analyst-001",
    toRole: "analyst",
    topic: null,
    messageType: "intel.bundle",
    payload: { symbols: ["TAO", "RNDR", "AKT"] },
    transportKind: "a2a",
    deliveryStatus: "received",
    durableRefId: "proof-intel-log-001",
    timestamp: "2026-04-25T09:01:40.000Z",
  },
  {
    id: "axl-intel-003",
    runId: intelRun.id,
    correlationId: "corr-intel-003",
    fromAgentId: "agent-analyst-001",
    fromRole: "analyst",
    toAgentId: "agent-publisher-001",
    toRole: "publisher",
    topic: null,
    messageType: "intel.publishable",
    payload: { intelId: "intel-ai-rotation-001", confidence: 88 },
    transportKind: "send",
    deliveryStatus: "received",
    durableRefId: "proof-intel-manifest-001",
    timestamp: "2026-04-25T09:03:30.000Z",
  },
]);

const intelEvents = z.array(agentEventSchema).parse([
  {
    id: "event-intel-001",
    runId: intelRun.id,
    agentId: "agent-orchestrator-001",
    agentRole: "orchestrator",
    eventType: "run_created",
    status: "success",
    summary: "Hourly mocked intel run created.",
    payload: { runMode: "mocked" },
    timestamp: DEMO_INTEL_RUN_STARTED_AT,
    correlationId: null,
    axlMessageId: null,
    proofRefId: null,
    signalId: null,
    intelId: null,
  },
  {
    id: "event-intel-002",
    runId: intelRun.id,
    agentId: "agent-research-001",
    agentRole: "research",
    eventType: "research_completed",
    status: "success",
    summary: "Narrative research completed for AI infrastructure rotation.",
    payload: { symbols: ["TAO", "RNDR", "AKT"] },
    timestamp: "2026-04-25T09:01:50.000Z",
    correlationId: "corr-intel-001",
    axlMessageId: "axl-intel-001",
    proofRefId: "proof-intel-log-001",
    signalId: null,
    intelId: null,
  },
  {
    id: "event-intel-003",
    runId: intelRun.id,
    agentId: "agent-analyst-001",
    agentRole: "analyst",
    eventType: "intel_ready",
    status: "success",
    summary: "Analyst converted the bundle into a publishable intel brief.",
    payload: { category: "narrative_shift", confidence: 88 },
    timestamp: "2026-04-25T09:03:00.000Z",
    correlationId: "corr-intel-002",
    axlMessageId: "axl-intel-002",
    proofRefId: "proof-intel-kv-001",
    signalId: null,
    intelId: "intel-ai-rotation-001",
  },
  {
    id: "event-intel-004",
    runId: intelRun.id,
    agentId: "agent-publisher-001",
    agentRole: "publisher",
    eventType: "report_published",
    status: "success",
    summary: "Intel summary posted to X and attached to the run manifest.",
    payload: { provider: "twitterapi", threadCount: 1 },
    timestamp: "2026-04-25T09:04:20.000Z",
    correlationId: "corr-intel-003",
    axlMessageId: "axl-intel-003",
    proofRefId: "proof-intel-post-001",
    signalId: null,
    intelId: "intel-ai-rotation-001",
  },
]);

const intelPost = outboundPostSchema.parse({
  id: "post-intel-001",
  runId: intelRun.id,
  signalId: null,
  intelId: intelRecord.id,
  target: "x",
  kind: "intel_summary",
  status: "posted",
  payload: {
    text: "Omen intel: AI infrastructure names kept absorbing mindshare while BTC stayed neutral. TAO / RNDR / AKT led the rotation.",
    thread: [
      "The swarm kept this as intel, not a signal, because BTC regime confirmation stayed incomplete and catalysts were mostly narrative-led.",
    ],
    metadata: { manifestRefId: "proof-intel-manifest-001" },
  },
  provider: "twitterapi",
  providerPostId: "tweet-intel-001",
  publishedUrl: "https://x.com/omen/status/1000000000000000002",
  lastError: null,
  createdAt: "2026-04-25T09:03:40.000Z",
  updatedAt: "2026-04-25T09:04:20.000Z",
  publishedAt: "2026-04-25T09:04:20.000Z",
});

const intelProofBundle = runProofBundleSchema.parse({
  runId: intelRun.id,
  manifestRefId: "proof-intel-manifest-001",
  artifactRefs: intelProofArtifacts,
});

export const demoSignalRunBundle = {
  run: signalRun,
  nodes: demoAgentNodes,
  signal: signalRecord,
  intel: null,
  axlMessages: signalMessages,
  events: signalEvents,
  proofs: signalProofArtifacts,
  proofBundle: signalProofBundle,
  outboundPosts: [signalPost],
};

export const demoIntelRunBundle = {
  run: intelRun,
  nodes: demoAgentNodes,
  signal: null,
  intel: intelRecord,
  axlMessages: intelMessages,
  events: intelEvents,
  proofs: intelProofArtifacts,
  proofBundle: intelProofBundle,
  outboundPosts: [intelPost],
};

export const demoRunBundleSchema = z.object({
  run: runSchema,
  nodes: z.array(agentNodeSchema),
  signal: signalSchema.nullable(),
  intel: intelSchema.nullable(),
  axlMessages: z.array(axlEnvelopeSchema),
  events: z.array(agentEventSchema),
  proofs: z.array(proofArtifactSchema),
  proofBundle: runProofBundleSchema,
  outboundPosts: z.array(outboundPostSchema),
});

export const demoRunBundles = z.array(demoRunBundleSchema).parse([
  demoSignalRunBundle,
  demoIntelRunBundle,
]);

export type DemoRunBundle = z.infer<typeof demoRunBundleSchema>;
